include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    dart_code_metrics

dart_code_metrics:
  rules:
    - avoid-unnecessary-setstate
    - prefer-moving-to-variable
    - no-equal-arguments
